About/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AboutUsView, FAQView, about


app_name = 'about'

router = DefaultRouter()
router.register(r'about-us', AboutUsView, basename='about-us')
router.register(r'FAQ', FAQView, basename='faq')


urlpatterns = [
    path('', about, name='about-view'),  # صفحه اصلی
    path('api/', include(router.urls)),
]

Blog/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'blogs'

router = DefaultRouter()
router.register(r'blog', BlogPostViewSet, basename='blog')

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blog-view'),  # صفحه اصلی
    path('blog/<int:pk>/', BlogPostDetailView.as_view(), name='detail'),

    path('api/', include(router.urls)),

]

Contact/urls.py
from django.urls import path
from . import views
from .views import EmailView

app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact-view'),  # صفحه اصلی
    path('api/', EmailView.as_view(), name='email'),

]

Home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home-view'),  # صفحه اصلی
]

Product/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from .views import SuspectViewSet, CaseViewSet, InterrogationViewSet, EvidenceViewSet, CommentViewSet

app_name = 'product'

router = DefaultRouter()
router.register(r'cases', CaseViewSet)
router.register(r'suspects', SuspectViewSet)
router.register(r'evidences', EvidenceViewSet)
router.register(r'interrogations', InterrogationViewSet)
router.register(r'comments', CommentViewSet)


urlpatterns = [
    path('play/<int:pk>/', views.play, name='play-view'),  # صفحه اصلی
    path('start/<int:pk>/', views.start, name='start-view'),  # صفحه اصلی
    path('suspects/<int:pk>/', views.suspects, name='suspects-view'),  # صفحه اصلی
    path('interrogation/<int:pk>/', views.interrogation, name='interrogation-view'),  # صفحه اصلی
    path('evidence/<int:pk>/', views.evidence, name='evidence-view'),  # صفحه اصلی
    path('result/<int:pk>/', views.result, name='result-view'),  # صفحه اصلی
    path('autopsy/<int:pk>/', views.autopsy, name='autopsy-view'),  # صفحه اصلی
    path('manager/case/', views.create_case, name='create-case-view'),  # صفحه اصلی
    path('manager/suspect/', views.create_suspect, name='creat-suspect-view'),  # صفحه اصلی
    path('manager/evidence/', views.create_evidence, name='create-evidence-view'),  # صفحه اصلی
    path('manager/interrogation/', views.create_interrogation, name='create-interrogation-view'),  # صفحه اصلی

    path('api/', include(router.urls)),

]

Seo/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

from .views import test_path

router = DefaultRouter()
router.register(r'seo', views.SEOPageView, basename='seo')
router.register(r'keyword', views.KeywordView, basename='keyword')

app_name = 'seo'

urlpatterns = [
    path('api/', include(router.urls)),
    path('test-path/', test_path, name='test_path'),

]

About/models.py
from django.core.validators import RegexValidator
from django.db import models


# Create your models here.

class FAQ(models.Model):
    icon = models.CharField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)


class AboutUs(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    # شماره تلفن (اعتبارسنجی شماره تلفن)
    phone_regex = RegexValidator(
        regex=r'^\+?(\d[\d().\s-]*)?\d{9,15}$',
        message="Phone number must be entered in a valid international format. Examples: '+1234567890', "
                "'+1 (234) 567-8901', or '+44-20-1234-5678'."
    )
    number = models.CharField(unique=True, validators=[phone_regex], max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    linkedin = models.URLField(verbose_name="linkedin", blank=True, null=True)
    instagram = models.URLField(verbose_name="instagram", blank=True, null=True)
    whatsApp = models.URLField(verbose_name="whatsApp", blank=True, null=True)
    telegram = models.URLField(verbose_name="telegram", blank=True, null=True)
    logo = models.FileField(upload_to='images/', null=True)
    image = models.FileField(upload_to='images/', null=True)
    video = models.FileField(upload_to='videos/', null=True)
    alt = models.CharField(max_length=255, null=True, blank=True)
    context = models.TextField(blank=True, null=True)

Category/models.py
from django.db import models


class CaseCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="نام دسته‌بندی پرونده")
    description = models.TextField(verbose_name="توضیحات دسته‌بندی پرونده", blank=True, null=True)

    def __str__(self):
        return self.name

Contact/forms.py
from django import forms
from .models import Contact  # مدل Contact که قبلاً تعریف کرده‌اید


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'message', 'file']

About/views.py
from django.shortcuts import render
from django.utils.translation import get_language, get_language_bidi
from django.views.decorators.cache import cache_page
from rest_framework.viewsets import ModelViewSet
from User.views import get_or_create_temporary_user, save_user_device_info, log_user_activity
from .models import AboutUs, FAQ
from .serializers import AboutUsSerializer, FAQSerializer


@cache_page(60 * 15)
def about(request):
    current_language = get_language()
    is_bidi = get_language_bidi()
    aboutUs = AboutUs.objects.first()
    faq = FAQ.objects.all()

    if request.user.is_authenticated:
        user = request.user
    else:
        user = get_or_create_temporary_user(request)
        save_user_device_info(request, user)

    log = log_user_activity(request, request.build_absolute_uri(), user)

    return render(request, 'main/about.html', {'LANGUAGE_CODE': current_language,
                                               'LANGUAGE_BIDI': is_bidi,
                                               'About': aboutUs,
                                               'FAQ': faq,
                                               'activity_log_id': log.id,
                                               })


# _____________________________ Class Based Views for developing API ________________________________


class AboutUsView(ModelViewSet):
    queryset = AboutUs.objects.all()
    serializer_class = AboutUsSerializer


class FAQView(ModelViewSet):
    queryset = FAQ.objects.all()
    serializer_class = FAQSerializer

Blog/views.py
from django.db.models import Q
from django.utils.translation import get_language
from django.views.generic import ListView, DetailView
from rest_framework import viewsets
from rest_framework.generics import get_object_or_404
from About.models import AboutUs
from Blog.models import BlogPost
from Blog.serializers import BlogPostSerializer


# لیست مقالات
class BlogPostListView(ListView):
    model = BlogPost
    template_name = "main/blog.html"
    context_object_name = "blog_posts"
    paginate_by = 10  # تعداد مقالات در هر صفحه

    def get_queryset(self):
        queryset = BlogPost.objects.all().order_by("-published_date")
        filters = Q()
        author = self.request.GET.get("author")
        search = self.request.GET.get("search")

        if author:
            filters &= Q(author__username__icontains=author)
        if search:
            filters &= Q(title__icontains=search)

        return queryset.filter(filters)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_posts'] = BlogPost.objects.count()  # تعداد کل مقالات
        context['About'] = AboutUs.objects.first()

        return context


# جزئیات مقاله
class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = "main/blogpost.html"
    context_object_name = "blog_post"

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(BlogPost, id=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_language'] = get_language()  # زبان جاری را اضافه می‌کنیم

        page_title = self.get_page_title()  # عنوان صفحه
        page_content = self.get_page_content()  # توصیف صفحه
        page_image = self.get_page_image()

        meta_title = self.get_meta_title()  # عنوان صفحه
        meta_description = self.get_meta_description()  # توصیف صفحه
        meta_keywords = self.get_meta_keywords()  # کلمات کلیدی
        canonical_url = self.request.build_absolute_uri(self.request.path)

        context['page_title'] = page_title
        context['page_content'] = page_content
        context['page_image'] = page_image

        context['meta_title'] = meta_title
        context['meta_description'] = meta_description
        context['meta_keywords'] = meta_keywords
        context['canonical_url'] = canonical_url

        return context

    def get_page_title(self):
        # شما می‌توانید عنوان صفحه را بر اساس عنوان مقاله بسازید
        blog_post = self.get_object()
        return blog_post.title

    def get_page_content(self):
        # توصیف صفحه می‌تواند از محتوای مقاله گرفته شود
        blog_post = self.get_object()
        return blog_post.content  # یا هر فیلدی که توصیف کوتاهی از مقاله باشد

    def get_page_image(self):
        # کلمات کلیدی می‌تواند بر اساس دسته‌بندی یا برچسب‌های مقاله باشد
        blog_post = self.get_object()
        return blog_post.image  # اگر مقاله دسته‌بندی‌ها داشته باشد

    def get_meta_title(self):
        # شما می‌توانید عنوان صفحه را بر اساس عنوان مقاله بسازید
        blog_post = self.get_object()
        return blog_post.meta_title

    def get_meta_description(self):
        # توصیف صفحه می‌تواند از محتوای مقاله گرفته شود
        blog_post = self.get_object()
        return blog_post.meta_description  # یا هر فیلدی که توصیف کوتاهی از مقاله باشد

    def get_meta_keywords(self):
        # کلمات کلیدی می‌تواند بر اساس دسته‌بندی یا برچسب‌های مقاله باشد
        blog_post = self.get_object()
        return blog_post.meta_keywords  # اگر مقاله دسته‌بندی‌ها داشته باشد


class BlogPostViewSet(viewsets.ModelViewSet):
    queryset = BlogPost.objects.all().order_by('-published_date')  # لیست مقالات مرتب‌شده بر اساس تاریخ انتشار
    serializer_class = BlogPostSerializer

Contact/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.utils.translation import get_language, get_language_bidi
from django.views.decorators.cache import cache_page
from django.core.mail import EmailMessage
from rest_framework.response import Response
from rest_framework.views import APIView

from About.models import AboutUs
from Contact.forms import ContactForm
from User.views import get_or_create_temporary_user, save_user_device_info, log_user_activity


@cache_page(60 * 15)
def contact(request):
    current_language = get_language()
    is_bidi = get_language_bidi()
    aboutUs = AboutUs.objects.first()

    if request.user.is_authenticated:
        user = request.user
    else:
        user = get_or_create_temporary_user(request)
        save_user_device_info(request, user)

    log = log_user_activity(request, request.build_absolute_uri(), user)

    return render(request, 'main/contact.html', {'LANGUAGE_CODE': current_language,
                                                 'LANGUAGE_BIDI': is_bidi,
                                                 'About': aboutUs,
                                                 'activity_log_id': log.id,

                                                 })


class EmailView(APIView):
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.data, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            file = form.cleaned_data.get('file')

            email_subject = f"Message from {name}"
            email_body = f"Name: {name}\nPhone: {phone}\nEmail: {email}\n\nMessage:\n{message}"

            email_message = EmailMessage(
                email_subject,
                email_body,
                'customer@phoenixfamily.co',  # فرستنده
                ['info@phoenixfamily.co']  # گیرنده
            )

            if file:
                email_message.attach(file.name, file.read(), file.content_type)

            try:
                # Send the email
                email_message.send()
                return Response({"message": "Email successfully sent"}, status=200)
            except Exception as e:
                # Handle errors while sending the email
                return Response({"error": f"Error sending email: {str(e)}"}, status=500)

        return Response({"error": form.errors}, status=400)

Home/views.py
from django.shortcuts import render
from django.utils.translation import get_language, get_language_bidi
from django.views.decorators.cache import cache_page

from Product.models import Case


@cache_page(60 * 15)
def home(request):
    current_language = get_language()
    is_bidi = get_language_bidi()

    products = Case.objects.all()

    return render(request, 'main/home.html', {'LANGUAGE_CODE': current_language, 'LANGUAGE_BIDI': is_bidi, 'products':products})

Podcast/views.py
from django.db.models import Q
from django.utils.translation import get_language
from django.views.generic import ListView, DetailView
from rest_framework import viewsets
from rest_framework.generics import get_object_or_404
from About.models import AboutUs
from .models import *
from .serializers import PodcastPostSerializer


class BlogPostListView(ListView):
    model = PodcastPost
    template_name = "main/podcast.html"
    context_object_name = "blog_posts"
    paginate_by = 10  # تعداد مقالات در هر صفحه

    def get_queryset(self):
        queryset = PodcastPost.objects.all().order_by("-published_date")
        filters = Q()
        author = self.request.GET.get("author")
        search = self.request.GET.get("search")

        if author:
            filters &= Q(author__username__icontains=author)
        if search:
            filters &= Q(title__icontains=search)

        return queryset.filter(filters)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_posts'] = PodcastPost.objects.count()  # تعداد کل مقالات
        context['About'] = AboutUs.objects.first()

        return context


# جزئیات مقاله
class PodcastPostDetailView(DetailView):
    model = PodcastPost
    template_name = "main/podcastpost.html"
    context_object_name = "podcast-post"

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(PodcastPost, id=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_language'] = get_language()  # زبان جاری را اضافه می‌کنیم

        page_title = self.get_page_title()  # عنوان صفحه
        page_content = self.get_page_content()  # توصیف صفحه
        page_image = self.get_page_image()

        meta_title = self.get_meta_title()  # عنوان صفحه
        meta_description = self.get_meta_description()  # توصیف صفحه
        meta_keywords = self.get_meta_keywords()  # کلمات کلیدی
        canonical_url = self.request.build_absolute_uri(self.request.path)

        context['page_title'] = page_title
        context['page_content'] = page_content
        context['page_image'] = page_image

        context['meta_title'] = meta_title
        context['meta_description'] = meta_description
        context['meta_keywords'] = meta_keywords
        context['canonical_url'] = canonical_url

        return context

    def get_page_title(self):
        # شما می‌توانید عنوان صفحه را بر اساس عنوان مقاله بسازید
        blog_post = self.get_object()
        return blog_post.title

    def get_page_content(self):
        # توصیف صفحه می‌تواند از محتوای مقاله گرفته شود
        blog_post = self.get_object()
        return blog_post.content  # یا هر فیلدی که توصیف کوتاهی از مقاله باشد

    def get_page_image(self):
        # کلمات کلیدی می‌تواند بر اساس دسته‌بندی یا برچسب‌های مقاله باشد
        blog_post = self.get_object()
        return blog_post.image  # اگر مقاله دسته‌بندی‌ها داشته باشد

    def get_meta_title(self):
        # شما می‌توانید عنوان صفحه را بر اساس عنوان مقاله بسازید
        blog_post = self.get_object()
        return blog_post.meta_title

    def get_meta_description(self):
        # توصیف صفحه می‌تواند از محتوای مقاله گرفته شود
        blog_post = self.get_object()
        return blog_post.meta_description  # یا هر فیلدی که توصیف کوتاهی از مقاله باشد

    def get_meta_keywords(self):
        # کلمات کلیدی می‌تواند بر اساس دسته‌بندی یا برچسب‌های مقاله باشد
        blog_post = self.get_object()
        return blog_post.meta_keywords  # اگر مقاله دسته‌بندی‌ها داشته باشد


class PodcastViewSet(viewsets.ModelViewSet):
    queryset = PodcastPost.objects.all().order_by('-published_date')  # لیست مقالات مرتب‌شده بر اساس تاریخ انتشار
    serializer_class = PodcastPostSerializer

templates/main/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/base_main.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ seo_title|default:"Crime" }}</title>
    <meta name="description" content="{{ seo_description }}">
    <meta name="keywords" content="{{ seo_keywords }}">
    <meta name="robots" content="index, follow">
    <link rel="stylesheet" href="{% static 'css/main-style.css' %}">
    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
    <link rel="canonical" href="{{ canonical_url|default:request.build_absolute_uri }}">
    <meta property="og:title" content="{{ seo_title|default:"Crime" }}">
    <meta property="og:description" content="{{ seo_description }}">
    <meta property="og:image" content="{% static 'images/logo.png' %}">
    <meta property="og:url" content="{{ canonical_url|default:request.build_absolute_uri }}">
    <meta name="twitter:title" content="{{ seo_title|default:"Crime" }}">
    <meta name="twitter:description" content="{{ seo_description }}">
    <meta name="twitter:image" content="{% static 'images/logo.png' %}">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/4a2a05a158.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>

    </style>

    <script type="application/ld+json">
    {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "Crime",
    "url": "https://crime.phoenixfamily.co",
    "logo": "https://crime.phoenixfamily.co/media/images/logo.png"
    }
    </script>


</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg shadow-sm">
        <div class="container d-flex justify-content-between align-items-center">

            <!-- لوگو سمت چپ -->
            <a class="navbar-brand" href="//phoenixfamily.co">
                <img src="{{ About.logo.url }}" alt="{% trans 'Logo' %}" class="d-inline-block align-text-top">
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
                <i class="fa-solid fa-bars custom-toggler"></i>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                {% block header %}

                {% endblock %}
            </div>
        </div>
    </nav>
</header>

<!-- محتوای متغیر -->
<div id="content">
    {% block content %}
    {% endblock %}
</div>

<footer>
    <div class="container py-4">
        {% block footer %}


        {% endblock %}

        <!-- کپی‌رایت -->
        <div class="row mt-4">
            <div class="col-12 text-center">
                <p class="mb-0 copyright text-muted">
                    &copy; 2024 PhoenixFamily. {% trans "All rights reserved." %}
                </p>
            </div>
        </div>
    </div>
</footer>


</body>


</html>

templates/main/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/blogpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/home.html
{% extends 'main/base_main.html' %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
</head>
<body>

{% block header %}
    <ul class="navbar-nav text-center">
        <li class="nav-item"><a class="nav-link active" href="{% url 'home:home-view' %}">{% trans "Home" %}</a></li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
               aria-expanded="false">{% trans "Products" %}</a>
            <ul class="dropdown-menu">
                {% for x in Products %}
                    <li><a class="dropdown-item" href="{% url 'products:product-view' x.id %}">{{ x.name|capfirst }}</a>
                    </li>
                {% endfor %}
            </ul>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'contact:contact-view' %}">{% trans "Contact Us" %}</a>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'about:about-view' %}">{% trans "About Us" %}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'blogs:blog-view' %}">{% trans "Blogs" %}</a></li>
    </ul>

    <div class="d-flex align-items-center ms-auto">
        <form action="{% url 'set_language' %}" method="post" class="ms-3 form-inline">
            {% csrf_token %}
            <select name="language" class="form-select form-select-sm w-auto"
                    onchange="this.form.submit()" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}"
                    aria-label="Change Language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
        </form>
    </div>

{% endblock %}


{% block content %}

    <div class="container my-5">
        <div class="row mt-4">
            <!-- Blog Post Card -->
            {% for product in products %}

                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if product.image %}
                            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}"/>
                        {% else %}
                            <img src="{% static 'images/banner.webp' %}" class="card-img-top" alt="{{ post.title }}"/>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.title }}</h5>
                            <p class="card-text">
                                سطح سختی:{{ product.difficulty_level }} | درجه سختی: {{ product.difficulty_number }} از
                                10
                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'product:play-view' product.id %}" target="_blank">Play</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}


{% block footer %}

    <div class="row align-items-center mt-5">
        <!-- لوگوی شرکت -->
        <div class="col-md-4 text-center mb-3 mb-md-0">
            <a href="//phoenixfamily.co">
                <img src="{{ About.logo.url }}" alt="{{ About.name }}" class="img-fluid"
                     style="max-width: 150px;">
            </a>
        </div>

        <!-- اطلاعات تماس -->
        <div class="col-md-4 text-center mb-3 mb-md-0">
            <h6 class="mb-2">{% trans "Contact Us" %}</h6>
            <p class="mb-1">
                <i class="fas fa-phone-alt contact-icon  me-2"></i>{% trans "Phone" %}: {{ About.number }}
            </p>
            <p class="mb-0">
                <i class="fas fa-envelope contact-icon me-2"></i>{% trans "Email" %}: {{ About.email }}
            </p>
        </div>

        <!-- شبکه‌های اجتماعی -->
        <div class="col-md-4 text-center right">
            <h6 class="mb-2">{% trans "Follow Us" %}</h6>
            <div class="social-icons">
                <a href="{{ About.instagram }}" class="me-3"><i class="fab fa-instagram fa-lg"></i></a>
                <a href="{{ About.telegram }}" class="me-3"><i class="fab fa-telegram fa-lg"></i></a>
                <a href="{{ About.whatsApp }}" class="me-3"><i class="fab fa-whatsapp fa-lg"></i></a>
                <a href="{{ About.linkedin }}"><i class="fa-brands fa-linkedin fa-lg"></i></a>
            </div>
        </div>
    </div>


{% endblock %}

</body>
</html>

templates/main/podcast.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/podcastpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>