CrimeProject/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from CrimeProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # مسیر پنل ادمین
    path('set_language/', include('django.conf.urls.i18n')),  # مسیر تغییر زبان
    path('not-supported/', TemplateView.as_view(template_name='games/support.html'), name='not_supported'),

]

urlpatterns += i18n_patterns(
    path('home/', include('Home.urls', namespace='home')),  # مسیر URLهای اپلیکیشن Home
    path('product/', include('Product.urls', namespace='product')),  # مسیر URLهای اپلیکیشن Home
    path('play/', include('Play.urls', namespace='play')),  # مسیر URLهای اپلیکیشن Home
    path('user/', include('User.urls', namespace='user')),  # مسیر URLهای اپلیکیشن Home
    path('about/', include('About.urls', namespace='about')),  # مسیر URLهای اپلیکیشن Home
    path('contact/', include('Contact.urls', namespace='contact')),  # مسیر URLهای اپلیکیشن Home
    path('blog/', include('Blog.urls', namespace='blog')),  # مسیر URLهای اپلیکیشن Home
    path('podcast/', include('Podcast.urls', namespace='podcast')),  # مسیر URLهای اپلیکیشن Home

)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home-view'),  # صفحه اصلی
]

Play/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import GameResultViewSet, CasePlayViewSet, success , failed

app_name = 'play'

router = DefaultRouter()
router.register(r'result', GameResultViewSet)
router.register(r'start', CasePlayViewSet)

urlpatterns = [
    path('success/<int:pk>/', success, name='success-view'),  # صفحه اصلی
    path('failed/<int:pk>/', failed, name='failed-view'),  # صفحه اصلی

    path('api/', include(router.urls)),
]

Product/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from .views import SuspectViewSet, CaseViewSet, InterrogationViewSet, EvidenceViewSet, CommentViewSet

app_name = 'product'

router = DefaultRouter()
router.register(r'cases', CaseViewSet)
router.register(r'suspects', SuspectViewSet)
router.register(r'evidences', EvidenceViewSet)
router.register(r'interrogations', InterrogationViewSet)
router.register(r'comments', CommentViewSet)


urlpatterns = [
    path('play/<int:pk>/', views.play, name='play-view'),  # صفحه اصلی
    path('start/<int:pk>/', views.start, name='start-view'),  # صفحه اصلی
    path('suspects/<int:pk>/', views.suspects, name='suspects-view'),  # صفحه اصلی
    path('interrogation/<int:pk>/', views.interrogation, name='interrogation-view'),  # صفحه اصلی
    path('evidence/<int:pk>/', views.evidence, name='evidence-view'),  # صفحه اصلی
    path('result/<int:pk>/', views.result, name='result-view'),  # صفحه اصلی
    path('autopsy/<int:pk>/', views.autopsy, name='autopsy-view'),  # صفحه اصلی
    path('manager/case/', views.create_case, name='create-case-view'),  # صفحه اصلی
    path('manager/suspect/', views.create_suspect, name='creat-suspect-view'),  # صفحه اصلی
    path('manager/evidence/', views.create_evidence, name='create-evidence-view'),  # صفحه اصلی
    path('manager/interrogation/', views.create_interrogation, name='create-interrogation-view'),  # صفحه اصلی

    path('api/', include(router.urls)),

]

Seo/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

from .views import test_path

router = DefaultRouter()
router.register(r'seo', views.SEOPageView, basename='seo')
router.register(r'keyword', views.KeywordView, basename='keyword')

app_name = 'seo'

urlpatterns = [
    path('api/', include(router.urls)),
    path('test-path/', test_path, name='test_path'),

]

User/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # سایر آدرس‌ها
    path('log-exit/', views.log_exit_time, name='log_exit_time'),
    path("user-observe/", views.UserObserve.as_view(), name="list_user"),
    path("user-observe/<str:number>/", views.UserObserve.as_view(), name="detail_user"),
    path("user-update/<str:number>/", views.UpdateUser.as_view()),
]

Play/models.py
from django.db import models

from Order.models import OrderItem
from Product.models import Suspect
from User.models import User


class CasePlay(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # orderItem = models.ForeignKey(OrderItem, on_delete=models.CASCADE, blank=True, null=True)
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, choices=[('in_progress', 'In Progress'), ('completed', 'Completed'),
                                                      ('cancelled', 'Cancelled')],
                              default='in_progress')


class CaeParticipant(models.Model):
    gameplay = models.ForeignKey(CasePlay, on_delete=models.CASCADE)
    participant = models.ForeignKey(User, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Participant {self.participant.number} in GamePlay {self.gameplay.id}"


class GameResult(models.Model):
    gameplay = models.ForeignKey(CasePlay, on_delete=models.CASCADE, blank=True, null=True)
    suspect = models.ForeignKey(Suspect, on_delete=models.CASCADE, blank=True, null=True)
    reason = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=50, choices=[('success', 'Success'), ('failed', 'Failed')])

    def __str__(self):
        return f"Result of GamePlay"

User/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core.validators import RegexValidator
from django.db import models
from django.utils.timezone import now


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, number, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('is_admin', True)

        return self.create_user(number, password, **other_fields)

    def create_user(self, number, password, **other_fields):
        user = self.model(number=number, **other_fields)
        user.set_password(password)
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    is_temporary = models.BooleanField(default=True)  # مشخص می‌کند کاربر موقت است یا نه

    # نام
    first_name = models.CharField(max_length=50, blank=True, null=True)
    # نام خانوادگی
    last_name = models.CharField(max_length=50, blank=True, null=True)

    # ایمیل
    email = models.EmailField(unique=True, blank=True, null=True)

    # شماره تلفن (اعتبارسنجی شماره تلفن)
    phone_regex = RegexValidator(
        regex=r'^\+?(\d[\d().\s-]*)?\d{9,15}$',
        message="Phone number must be entered in a valid international format. Examples: '+1234567890', "
                "'+1 (234) 567-8901', or '+44-20-1234-5678'."
    )
    number = models.CharField(unique=True, validators=[phone_regex], max_length=15, blank=True, null=True)

    # تاریخ تولد
    birth_date = models.DateField(blank=True, null=True)

    # تصویر پروفایل
    image = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    # جنسیت
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
    ]
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)

    is_staff = models.BooleanField(default=False, verbose_name="مدیر")
    is_active = models.BooleanField(default=True, verbose_name='فعال')
    is_admin = models.BooleanField(default=False, verbose_name='ادمین')

    # زمان ایجاد و به‌روزرسانی
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'number'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'birth_date', 'gender']

    objects = CustomAccountManager()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"


class UserDeviceInfo(models.Model):
    # نوع دستگاه (موبایل، تبلت، دسکتاپ)
    DEVICE_TYPES = [
        ('Mobile', 'Mobile'),
        ('Tablet', 'Tablet'),
        ('Desktop', 'Desktop'),
        ('Unknown', 'Unknown'),
    ]
    # مدل دستگاه (مثلاً iPhone 13 Pro)
    device_model = models.CharField(max_length=100, blank=True, null=True)
    device_type = models.CharField(max_length=10, choices=DEVICE_TYPES, default='Unknown')

    # سیستم‌عامل و نسخه (مثلاً Android 12)
    operating_system = models.CharField(max_length=50, blank=True, null=True)
    os_version = models.CharField(max_length=50, blank=True, null=True)

    # مرورگر و نسخه (مثلاً Chrome 119)
    browser = models.CharField(max_length=50, blank=True, null=True)
    browser_version = models.CharField(max_length=50, blank=True, null=True)

    # آدرس IP کاربر
    ip_address = models.GenericIPAddressField(blank=True, null=True)

    # منطقه جغرافیایی (کشور و شهر)
    country = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)

    # زمان ایجاد (برای ردیابی زمان)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_device_info')

    def __str__(self):
        return f"{self.device_type} - {self.device_model or 'Unknown'}"

    class Meta:
        verbose_name = "User Device Info"
        verbose_name_plural = "User Device Infos"


class UserActivityLog(models.Model):
    # اطلاعات کاربر (اگر کاربر احراز هویت شده باشد)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_activity_log')

    # صفحه بازدید شده
    visited_page = models.URLField()

    # زمان ورود به صفحه
    entry_time = models.DateTimeField(default=now)

    # زمان خروج از صفحه
    exit_time = models.DateTimeField(null=True, blank=True)

    # لینک‌های کلیک‌شده در صفحه
    clicked_links = models.TextField(null=True, blank=True)

    # کلیدواژه‌های جستجو شده
    search_keywords = models.TextField(null=True, blank=True)

    # محصولات یا خدمات مشاهده‌شده
    viewed_items = models.TextField(null=True, blank=True)

    # خطاهای رخ‌داده
    error_messages = models.TextField(null=True, blank=True)

    # زمان ایجاد و به‌روزرسانی
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def duration_on_page(self):
        """محاسبه مدت زمان حضور در صفحه"""
        if self.exit_time:
            return (self.exit_time - self.entry_time).total_seconds()
        return None

    def __str__(self):
        return f"Activity by {self.user or 'Anonymous'} on {self.visited_page}"

    class Meta:
        verbose_name = "User Activity Log"
        verbose_name_plural = "User Activity Logs"

Play/views.py
from django.shortcuts import render
from django.utils import timezone
from django.utils.translation import get_language, get_language_bidi
from rest_framework import viewsets, status
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from CrimeProject.decorators import session_auth_required
from Play.models import CasePlay, GameResult
from Play.serializers import GameResultSerializer, CasePlaySerializer
from Product.models import Suspect, Case, Evidence
from User.views import get_or_create_temporary_user, save_user_device_info, log_user_activity


@session_auth_required
def success(request, pk):
    current_language = get_language()
    is_bidi = get_language_bidi()
    product = get_object_or_404(Case, id=pk)
    evidences = Evidence.objects.filter(case=pk)

    log = log_user_activity(request, request.build_absolute_uri(), request.user)

    return render(request, 'games/success.html', {
        'LANGUAGE_CODE': current_language,
        'LANGUAGE_BIDI': is_bidi,
        'case': product,
        'evidences': evidences,
        'activity_log_id': log.id,

    })


@session_auth_required
def failed(request, pk):
    current_language = get_language()
    is_bidi = get_language_bidi()
    product = get_object_or_404(Case, id=pk)
    evidences = Evidence.objects.filter(case=pk)

    log = log_user_activity(request, request.build_absolute_uri(), request.user)

    return render(request, 'games/failed.html', {
        'LANGUAGE_CODE': current_language,
        'LANGUAGE_BIDI': is_bidi,
        'case': product,
        'evidences': evidences,
        'activity_log_id': log.id,

    })


class CasePlayViewSet(viewsets.ModelViewSet):
    queryset = CasePlay.objects.all()
    serializer_class = CasePlaySerializer
    permission_classes = [IsAuthenticated]

    def create(self, request, *args, **kwargs):

        if self.request.user.is_authenticated:
            user = self.request.user
        else:
            user = get_or_create_temporary_user(request)

        save_user_device_info(request, user)

        case_play_data = {
            'user': user.id,
            'status': 'in_progress',
        }

        serializer = self.serializer_class(data=case_play_data)
        serializer.is_valid(raise_exception=True)
        saved_instance = serializer.save()

        request.session['play_id'] = saved_instance.id
        request.session.modified = True

        return Response(serializer.data, status=status.HTTP_201_CREATED)


class GameResultViewSet(viewsets.ModelViewSet):
    queryset = GameResult.objects.all()
    serializer_class = GameResultSerializer
    permission_classes = [IsAuthenticated]

    def create(self, request, *args, **kwargs):
        """
        متد شخصی‌سازی شده برای ایجاد GameResult و پایان بازی.
        """
        # دریافت اطلاعات از درخواست
        play_id = request.session.get('play_id')  # ID بازی که می‌خواهیم نتیجه‌اش را ثبت کنیم
        suspect_id = request.data.get('suspect')

        try:
            suspect = Suspect.objects.get(id=suspect_id)  # پیدا کردن مظنون
        except Suspect.DoesNotExist:
            return Response({"detail": "suspect not found."}, status=status.HTTP_404_NOT_FOUND)

        status_result = 'success' if suspect.role == 'murderer' else 'failed'

        game_play_data = {
            'gameplay': play_id,
            'suspect': request.data.get('suspect'),
            'reason': request.data.get('reason'),
            'status': status_result
        }

        try:
            # بازی را پیدا کنید
            case_play = CasePlay.objects.get(id=play_id)
        except CasePlay.DoesNotExist:
            return Response({"detail": "Game not found."}, status=status.HTTP_404_NOT_FOUND)

        serializer = self.serializer_class(data=game_play_data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()

        # به‌روزرسانی وضعیت بازی در مدل CasePlay
        case_play.status = 'completed'
        case_play.completed_at = timezone.now()
        case_play.save()

        # بازگشت پاسخ
        return Response(serializer.data, status=status.HTTP_201_CREATED)

templates/games/evidence.html
{% extends 'games/base_game.html' %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index, follow"> <!-- اجازه ایندکس و دنبال کردن لینک‌ها -->
    <title>{% block title %}{% trans 'شواهد و مدارک' %}{% endblock %}</title> <!-- عنوان صفحه -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/4a2a05a158.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">


</head>
<body>

 {% block header %}
     <div class="header mt-2">
     <h3>{% trans 'شواهد و مدارک' %}</h3>
     </div>
        {% endblock %}


 {% block content %}


<div class="container" style="margin-bottom: 150px">
    <!-- Evidence Cards -->
  <div class="row mx-md-5 justify-content-center">

        {% for evidence in evidences %}
            {% if evidence.status == "Locked" %}
                <div class="col-12 col-md-4 mt-4 d-flex justify-content-center">
                    <div class="card">
                        <img src="{{ evidence.image.url }}" class="card-img-top" alt="Locked Evidence">
                        <div class="card-body">
                            <h5 class="card-title">{{ evidence.title }}</h5>
                            <p class="card-text">{{ evidence.description | truncatechars:20 }}</p>
                            <input type="text" class="form-control mb-2" placeholder="Enter Code">
                        </div>
                         <div class="card-footer">
                            <a href="{% url 'product:autopsy-view' evidence.id %}" target="_blank">{% trans 'مشاهده جزییات' %}</a>
                        </div>
                    </div>
                </div>

            {% else %}
                <div class="col-12 col-md-4 mt-4 d-flex justify-content-center">
                    <div class="card">
                        <img src="{{ evidence.image.url }}" class="card-img-top" alt="Evidence">
                        <div class="card-body">
                            <h5 class="card-title">{{ evidence.title }}</h5>
                            <p class="card-text">{{ evidence.description }}</p>
                        </div>
                        <div class="card-footer">
                            {% if evidence.evidence_type == 'AUTOPSY' %}
                                <a href="{% url 'product:autopsy-view' evidence.id %}">{% trans 'مشاهده جزییات' %}</a>
                            {% elif evidence.evidence_type == 'OTHER' %}
                                <a href="//{{ evidence.details }}" target="_blank">{% trans 'مشاهده جزییات' %}</a>
                                {% elif evidence.evidence_type == 'PHOTO'  %}
                                <a onclick="openModal('{{ evidence.file.url }}')">
                                    {% trans 'مشاهده جزییات' %}
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>

            {% endif %}
        {% endfor %}
    </div>
</div>

     <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
         <div class="modal-dialog">
             <div class="modal-content">
                 <div class="modal-header">
                     <i class="fa-solid fa-xmark" data-bs-dismiss="modal" aria-label="Close" style="color: #d32f2f; cursor: pointer"></i>
                 </div>
                 <div class="modal-body">
                     <img class="img-fluid" id="modalImage" alt="evidence" src="">
                 </div>
             </div>
         </div>
     </div>

    <script>
        // فانکشن برای باز کردن modal
        function openModal(imgSrc) {
            // تنظیم تصویر و کپشن برای modal
            document.getElementById('modalImage').src = imgSrc;

            // نمایش modal
            var myModal = new bootstrap.Modal(document.getElementById('imageModal'));
            myModal.show();
  }

</script>

     <script>
    const activityLogId = "{{ activity_log_id|default:'' }}"; // مطمئن شوید این مقدار در تمپلیت مقداردهی شده است

    window.addEventListener('beforeunload', function (event) {
        if (activityLogId) {
            const data = {
                activity_log_id: activityLogId,
                exit_time: new Date().toISOString(),
            };

            // ارسال داده با fetch به جای sendBeacon
            fetch("{% url 'user:log_exit_time' %}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": "{{ csrf_token }}", // اضافه کردن CSRF Token
                },
                body: JSON.stringify(data),
            })
            .then(response => {
                if (!response.ok) {
                    console.error("Failed to log exit time:", response.statusText);
                }
            })
            .catch(error => console.error("Error logging exit time:", error));
        } else {
            console.warn("Activity log ID is missing; exit time not logged.");
        }
    });
</script>

 {% endblock %}


{% block footer_buttons %}

     <div class="container-fluid d-flex align-items-center justify-content-between pb-2  py-3 px-3">
        <a href="{% url 'product:suspects-view' case.id %}" class="btn {% if LANGUAGE_BIDI %}float-end{% else %}float-start{% endif %}">
            <i class="fa-solid previous-icon {% if LANGUAGE_BIDI %} fa-arrow-right rtl {% else %} fa-arrow-left ltr{% endif %}"></i>
            <span>{% trans "مظنونین" %}</span>
        </a>

     <a href="{% url 'product:result-view' case.id %}" class="btn {% if LANGUAGE_BIDI %}float-start{% else %}float-end{% endif %}">
            <span>{% trans "جواب" %}</span>
            <i class="fa-solid next-icon {% if LANGUAGE_BIDI %} fa-arrow-left rtl {% else %} fa-arrow-right ltr{% endif %}"></i>
        </a>
    </div>

{% endblock %}

</body>
</html>

templates/games/suspects.html
{% extends 'games/base_game.html' %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index, follow"> <!-- اجازه ایندکس و دنبال کردن لینک‌ها -->
    <title>{% block title %}{% trans 'مظنونین' %}{% endblock %}</title> <!-- عنوان صفحه -->

</head>
<body>

 {% block header %}
     <div class="header mt-2">
     <h3>{% trans 'مظنونین' %}</h3>
     </div>
        {% endblock %}

 {% block content %}


{#<div class="container mt-3 mx-5">#}
{#    <div class="input-group" dir="rtl">#}
{#        <label for="search-input"></label>#}
{#        <input type="text" id="search-input" class="form-control" placeholder="جست و جو ...">#}
{#        <div class="input-group-append">#}
{#            <button id="search-button" class="btn" type="button">#}
{#                <i class="fas fa-search"></i>#}
{#            </button>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

 <div class="container" style="margin-bottom: 150px">
  <div class="row mx-md-5 justify-content-center">
    <!-- Blog Post Card -->

      {% for x in suspects %}
    <div class="col-12 col-md-4 {% if forloop.first %} mt-4 {% else %} mt-4 {% endif %} d-flex justify-content-center">
      <div class="card">
          {% if x.image %}
              <img src="{{ x.image.url }}" class="card-img-top" alt="{{ x.name }}" />
             {% else %}
             {% if x.gender == "male" %}
                 <img src="{% static 'images/suspect 1.webp' %}" class="card-img-top" alt="Suspect Image" />
                 {% else %}
                 <img src="{% static 'images/suspect 2.webp' %}" class="card-img-top" alt="Suspect Image" />
                 {% endif %}
             {% endif %}

        <div class="card-body">
          <h5 class="card-title">{{ x.name }}</h5>
          <p class="card-text">{% trans "سن:" %} {{ x.age }} | {% trans "جنسیت:" %} {{ x.get_gender_display }} | {% trans "ارتباط با مقتول:" %} {{ x.relationship_with_victim }}</p>
        </div>
        <div class="card-footer">
          <a href="{% url 'product:interrogation-view' x.id %}">{% trans 'اتاق بازجویی' %}</a>
        </div>
      </div>
    </div>
      {% endfor %}


  </div>
</div>


<script>
    function searchFunction() {
    var input, filter, posts, post, title, i, txtValue;
    input = document.getElementById('searchInput');
    filter = input.value.toLowerCase();
    posts = document.getElementsByClassName('blog-post');

    // Loop through all blog posts and hide those that don't match the search
    for (i = 0; i < posts.length; i++) {
        post = posts[i];
        title = post.getElementsByTagName('h4')[0];
        txtValue = title.textContent || title.innerText;

        if (txtValue.toLowerCase().indexOf(filter) > -1) {
            post.style.display = "";
        } else {
            post.style.display = "none";
        }
    }
}
</script>

     <script>
    const activityLogId = "{{ activity_log_id|default:'' }}"; // مطمئن شوید این مقدار در تمپلیت مقداردهی شده است

    window.addEventListener('beforeunload', function (event) {
        if (activityLogId) {
            const data = {
                activity_log_id: activityLogId,
                exit_time: new Date().toISOString(),
            };

            // ارسال داده با fetch به جای sendBeacon
            fetch("{% url 'user:log_exit_time' %}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": "{{ csrf_token }}", // اضافه کردن CSRF Token
                },
                body: JSON.stringify(data),
            })
            .then(response => {
                if (!response.ok) {
                    console.error("Failed to log exit time:", response.statusText);
                }
            })
            .catch(error => console.error("Error logging exit time:", error));
        } else {
            console.warn("Activity log ID is missing; exit time not logged.");
        }
    });
</script>

 {% endblock %}

 {% block fab_buttons %}
  <div class="sub-button shadow">
    <a id="showFullTextBtn" target="_blank">
      <i class="fa-solid fa-stop"></i>
    </a>
  </div>

    <script>
    document.getElementById("showFullTextBtn").addEventListener("click", function() {
            typingText.textContent = text; // نمایش کامل متن
            index = text.length; // به روز رسانی ایندکس برای جلوگیری از تایپ دوباره
             });
    </script>

        {% endblock %}


{% block footer_buttons %}

     <div class="container-fluid d-flex align-items-center justify-content-between pb-2  py-3 px-3">
        <a href="{% url 'product:start-view' case.id %}" class="btn {% if LANGUAGE_BIDI %}float-end{% else %}float-start{% endif %}">
            <i class="fa-solid previous-icon {% if LANGUAGE_BIDI %} fa-arrow-right rtl {% else %} fa-arrow-left ltr{% endif %}"></i>
            <span>{% trans "گزارش" %}</span>
        </a>

     <a href="{% url 'product:evidence-view' case.id %}" class="btn {% if LANGUAGE_BIDI %}float-start{% else %}float-end{% endif %}">
            <span>{% trans "مدارک" %}</span>
            <i class="fa-solid next-icon {% if LANGUAGE_BIDI %} fa-arrow-left rtl {% else %} fa-arrow-right ltr{% endif %}"></i>
        </a>
    </div>


{% endblock %}
</body>
</html>